### PR TITLE
Fix regex to account for if there is no {} present in compendium match

### LINKED ISSUE #30: Dragging staff of fire in fails
match looks like this, which results in this exception.

image

```
main.js:217  Uncaught (in promise) TypeError: undefined. strs is not iterable
[Detected 1 package: pf2e-staves]
    at createStaveSpellcastingEntry (main.js:217:27)
    at Object.fn (main.js:34:12)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at ClientDatabaseBackend.callback (foundry.js:12613:13)
    at foundry.js:12594:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleCreateEmbeddedDocuments (foundry.js:12594:33)
    at ClientDatabaseBackend._createEmbeddedDocuments (foundry.js:12499:17)
    at async Proxy.createDocuments (commons.js:6110:23)
```

### PR DESCRIPTION
**Pull request by etriebe**
Dragging Staff of Fire into actor sheet no longer fails.

image

Fix #30

### CODE REVIEW

File: scripts/main.js [hunk 1]
```diff
@@ -213,7 +213,7 @@ async function createStaveSpellcastingEntry(stave, actor, existingEntry = null)
         const match = description.match(regex);
         if (!match) continue;
 
-        const strs = match[0].match(/(@UUID\[Compendium\.|@Compendium\[)(.*?)].*?}/g);
+        const strs = match[0].match(/(@UUID\[Compendium\.|@Compendium\[)(.*?)]({.*?})?/g);
```
Comment (etriebe) [inline scripts/main.js:216]: This makes the {} portion optional by placing it in a group and making that whole group optional.

Comment (etriebe) [reply scripts/main.js:216]: @jessev14 Can you help take a look? This fixed issues for me locally. 😄
